/**
 * The complimentary close every proposal ends with.
 *
 * Deliberately NOT generated by Claude. It is a fixed string whose only
 * variable — the salesperson's name — is already a column on the proposals
 * table, so asking a model to reproduce it costs tokens, drifts in wording
 * between drafts, and carries no guarantee it appears at all. Rendered here
 * instead, it is identical in the PDF, on the share page and in the
 * salesperson's own review view, every time.
 *
 * The trade: it is not editable per proposal. That is the intent — this is
 * company sign-off, not proposal content. The system prompt
 * (lib/prompts/system.ts, rule 10) tells Claude not to write its own, so a
 * proposal never ends up with two.
 *
 * No 'server-only' here on purpose: the PDF renderer, the client-facing
 * server component and the editor's client component all read these.
 */
export const PROPOSAL_CLOSE = {
  farewell: 'Looking forward to working together.',
  signoff: 'Warm regards,',
  company: 'Koya Talent',
} as const;
